version: "3.8"

services:
  web:
    image: ghcr.io/yarovision/exchange:latest
    container_name: kronos-web
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.kronos.rule=Host(`btc.lexis.blog`)
      - traefik.http.routers.kronos.entrypoints=websecure
      - traefik.http.routers.kronos.tls.certresolver=letsencrypt
      - traefik.http.services.kronos.loadbalancer.server.port=7070
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
